# ################################################## #
# AUTOR: ANTONIO.DUARTE
# ################################################## #

server:
  port: 8080
  
spring:
  application:
    name: '@project.artifactId@'

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:    url: jdbc:h2:mem:test
    username: sa
    password: 
  jpa:    database: h2
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

arquivos:
  filmes: 'movielist.csv'